from __future__ import annotations

import re
from typing import Any

# --- CI assertion domain registry specs (generated by B4.R4 migration) ---

ASSERTION_SPECS: tuple[dict[str, Any], ...] = ({'id': 'native.intern_metadata_status_consistent',
  'title': 'Intern metadata/status consistent',
  'description': 'intern metadata resolver、status.md metadata 和 CLI status JSON 的 project/type/status 字段一致。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 14},
 {'id': 'native.relay_registry_entry',
  'title': 'Relay registry entry',
  'description': 'daemon chat lookup 与 relay registry 中存在 project-scoped intern/chat mapping。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 15},
 {'id': 'native.tree_projection_contains',
  'title': 'Tree projection contains intern',
  'description': 'TreeView/list projection 暴露 created intern、status、project 和 backend type。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 17},
 {'id': 'native.intern_create_rollback',
  'title': 'Intern create rollback',
  'description': 'duplicate/invalid/backend/workspace create failure 后无额外 metadata、runtime、session 或 chat registry 残留。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 18},
 {'id': 'native.delete_force_guard',
  'title': 'Delete force guard',
  'description': 'Idle 普通删除、Working 非 force 拒绝、force delete 清理 metadata/runtime/session/task/group registry 的行为符合 '
                 'contract。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 31},
 {'id': 'native.task_creation_stops_before_assignment',
  'title': 'Task scaffold only',
  'description': '任务已创建但未分配，目标文件未变化。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 32},
 {'id': 'native.no_merge_before_approval',
  'title': 'No merge before approval',
  'description': '用户批准前 PR/MR 或本地 master 不得被合入。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 33},
 {'id': 'native.mode_switch_blocked_by_active_intern',
  'title': 'Mode switch blocked',
  'description': 'active intern 工作中时危险 mode switch 被阻止。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 34},
 {'id': 'native.goal_delivered',
  'title': 'Goal delivered',
  'description': 'goal set/cancel relay API 返回 delivered。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 35},
 {'id': 'native.helper_lifecycle',
  'title': 'Helper lifecycle',
  'description': 'helper start/status/invite-owner/stop 关键状态正确。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 36},
 {'id': 'native.peer_transport_delivered',
  'title': 'Peer transport delivered',
  'description': 'peer next/stop/default transport 返回 delivered 或可诊断的明确失败分类。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 39},
 {'id': 'native.peer_transport_target_scoped',
  'title': 'Peer target scoped',
  'description': 'peer 消息只路由到目标 intern/project，不污染其他目标。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 40},
 {'id': 'native.peer_transport_deduplicated',
  'title': 'Peer deduplicated',
  'description': '重复 peer 投递不会重复执行同一个目标动作。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 41},
 {'id': 'native.goal_transport_consistent',
  'title': 'Goal transport consistent',
  'description': 'goal set/cancel receipt 与目标 daemon/relay 可见状态一致。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 42},
 {'id': 'native.goal_cancel_clears_context',
  'title': 'Goal cancel clears context',
  'description': 'goal cancel 后 stale goal 不再进入下一轮 prompt/context。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 43},
 {'id': 'native.helper_service_lifecycle',
  'title': 'Helper service lifecycle',
  'description': 'helper status/stop 后 helper runtime、metadata 和 session registry 状态一致。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 44},
 {'id': 'native.helper_stop_blocks_routing',
  'title': 'Helper stop blocks routing',
  'description': 'helper stop 后旧 helper 消息不可继续路由到停止的 helper runtime。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 45},
 {'id': 'native.master_file_content',
  'title': 'Master file content',
  'description': 'merge 后 master 文件内容与 marker 完全一致。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 49},
 {'id': 'native.metadata_completed',
  'title': 'Metadata completed',
  'description': 'task README Completed 且 intern status 回到 Idle。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 50},
 {'id': 'f.task_metadata_cli_consistent',
  'title': 'F task metadata CLI consistent',
  'description': 'F_0024 verifies task metadata line parsing, list/status/internal task-list visibility, task-delete '
                 'confirmation, in-progress guard, and local-only delete reports.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 74},
 {'id': 'f.peer_mailbox_goal_local_consistent',
  'title': 'F peer mailbox goal local consistent',
  'description': 'F_0025 verifies peer next/stop/default routing, structured peer failures, mailbox storage plus '
                 'daemon HTTP send/list/mark-read routes, and goal failure/cancel contracts.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 75},
 {'id': 'f.askuser_codex_local_consistent',
  'title': 'F AskUser Codex local consistent',
  'description': 'F_0026 verifies Codex request_user_input payload/card/resume behavior plus generic AskUser '
                 'permission, timeout, cancel, and duplicate callback controls.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 76},
 {'id': 'f.task_treeview_projection_consistent',
  'title': 'F task TreeView projection consistent',
  'description': 'F_0023 verifies on an existing debug deployment that task TreeView grouping, README open behavior, '
                 'tooltip/raw PR, InProgress PR description formatting, and line-3 metadata parser boundary evidence '
                 'remain consistent.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 79},
 {'id': 'f.task_delete_gui_contract_consistent',
  'title': 'F task delete GUI contract consistent',
  'description': 'F_0024 verifies on an existing debug deployment that intern.deleteTask item/QuickPick/cancel/no-task '
                 'paths, Open/Completed success, InProgress rejection, and internal task-delete CLI equivalence remain '
                 'consistent.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 80},
 {'id': 'f.intern_delete_force_guard_consistent',
  'title': 'F intern delete force guard consistent',
  'description': 'F_0050 verifies internctl delete refuses Working interns without --force, --force cleans '
                 'runtime/session/intern/task metadata, and VS Code Force Delete Intern delegates --force without real '
                 'Feishu or LLM resources.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 104},
 {'id': 'native.no_team_or_non_codex_fixture',
  'title': 'No team or non-Codex fixture',
  'description': 'case-scoped fixture projection/session registry 不包含 team intern 或非 Codex backend 残留。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 105})


def _check(name: str, ok: bool, detail: dict[str, Any]) -> dict[str, Any]:
    return {"name": name, "ok": bool(ok), "detail": detail}


def _safe_label(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]+", "_", value)


def fixture_intern_contract_checks(
    role_name: str,
    *,
    metadata: dict[str, Any] | None = None,
    status_path: str,
    status_path_exists: bool,
    knowledge_path: str,
    knowledge_path_exists: bool,
    runtime: str,
    runtime_exists: bool,
    hook_state_path: str,
    hook_state_exists: bool,
    session_key: str,
    session_entry: dict[str, Any],
    status_meta: dict[str, Any],
    expected_type: str,
    expected_role: str,
    expected_team_id: str = "",
) -> dict[str, Any]:
    metadata_detail = metadata or {"status_path": status_path, "knowledge_path": knowledge_path}
    detail = {
        "metadata": metadata_detail,
        "status_path": status_path,
        "knowledge_path": knowledge_path,
        "runtime": runtime,
        "hook_state": hook_state_path,
        "session_key": session_key,
        "entry": session_entry,
        "status_meta": status_meta,
        "expected_type": expected_type,
        "expected_role": expected_role,
        "expected_team_id": expected_team_id,
    }
    team_ok = status_meta.get("team_id") == expected_team_id if expected_team_id else not status_meta.get("team_id")
    return {
        "detail": detail,
        "checks": [
            _check(f"{role_name}_status_exists", status_path_exists, {"status_path": status_path, "metadata": metadata_detail}),
            _check(f"{role_name}_knowledge_exists", knowledge_path_exists, {"knowledge_path": knowledge_path}),
            _check(f"{role_name}_runtime_exists", runtime_exists, {"runtime": runtime}),
            _check(f"{role_name}_hook_state_exists", hook_state_exists, {"hook_state": hook_state_path}),
            _check(
                f"{role_name}_session_registry_type",
                isinstance(session_entry, dict) and session_entry.get("type") == expected_type,
                {"session_key": session_key, "entry": session_entry},
            ),
            _check(f"{role_name}_status_role", status_meta.get("role") == expected_role, {"status_meta": status_meta}),
            _check(
                f"{role_name}_status_team" if expected_team_id else f"{role_name}_status_no_team",
                team_ok,
                {"status_meta": status_meta},
            ),
        ],
    }


def metadata_status_consistent_checks(
    workspace: dict[str, Any],
    intern: str,
    *,
    metadata: dict[str, Any],
    status_path: str,
    status_path_exists: bool,
    status_meta: dict[str, Any],
    status_json: dict[str, Any],
    session_entries: dict[str, Any],
    expected_status: str,
    expected_type: str = "codex",
) -> dict[str, Any]:
    session_types = {str(entry.get("type") or "") for entry in session_entries.values() if isinstance(entry, dict)}
    detail = {
        "metadata": metadata,
        "status_meta": status_meta,
        "status_json": status_json,
        "session_entries": session_entries,
        "expected_type": expected_type,
    }
    returned = {
        "metadata": metadata,
        "status_path": status_path,
        "status_meta": status_meta,
        "status_json": status_json,
        "session_entries": session_entries,
    }
    return {
        "detail": detail,
        "returned": returned,
        "checks": [
            _check(
                "metadata_status_consistent_" + intern,
                status_path_exists
                and status_meta.get("status") == expected_status
                and status_json.get("status") == expected_status
                and status_json.get("project") == workspace["display"]
                and status_json.get("workspace_id") == workspace["workspace_id"]
                and expected_type in session_types,
                detail,
            ),
        ],
    }


def no_team_or_non_codex_fixture_checks(
    case_no: str,
    *,
    list_items: list[dict[str, Any]],
    session_items: dict[str, Any],
) -> dict[str, Any]:
    violations = []
    for item in list_items:
        if item.get("type") != "codex":
            violations.append({"kind": "non_codex_list_item", "item": item})
        if item.get("team_id"):
            violations.append({"kind": "team_list_item", "item": item})
    for key, entry in session_items.items():
        if isinstance(entry, dict) and entry.get("type") != "codex":
            violations.append({"kind": "non_codex_session_entry", "key": key, "entry": entry})
    detail = {"list_items": list_items, "session_items": session_items, "violations": violations}
    return {
        "detail": detail,
        "checks": [
            _check("no_team_or_non_codex_fixture_" + case_no, not violations, detail),
        ],
    }


def tree_projection_contains_checks(
    workspace: dict[str, Any],
    intern: str,
    item: dict[str, Any],
    *,
    expected_status: str,
    expected_type: str = "codex",
) -> dict[str, Any]:
    return {
        "detail": item,
        "checks": [
            _check(
                "tree_projection_contains_" + intern,
                item.get("status") == expected_status
                and item.get("type") == expected_type
                and item.get("project") == workspace["display"]
                and item.get("workspace_id") == workspace["workspace_id"],
                item,
            ),
        ],
    }


def no_intern_artifacts_checks(
    intern: str,
    *,
    runtime: str,
    runtime_exists: bool,
    session_entries: dict[str, Any],
    relay: dict[str, Any],
) -> dict[str, Any]:
    detail = {
        "runtime": runtime,
        "runtime_exists": runtime_exists,
        "session_entries": session_entries,
        "relay": relay,
    }
    return {
        "detail": detail,
        "checks": [
            _check(
                "no_intern_artifacts_" + _safe_label(intern),
                not runtime_exists and not session_entries,
                detail,
            ),
        ],
    }


def intern_removed_checks(
    intern: str,
    *,
    status_path: str,
    status_exists: bool,
    knowledge_path: str,
    knowledge_exists: bool,
    runtime: str,
    runtime_exists: bool,
    task_dir: str,
    task_exists: bool,
    session_entries: dict[str, Any],
    relay: dict[str, Any],
    tmux: dict[str, Any],
    expect_tmux_absent: bool,
    tmux_absent_ok: bool,
) -> dict[str, Any]:
    detail = {
        "status_path": status_path,
        "knowledge_path": knowledge_path,
        "runtime": runtime,
        "task_dir": task_dir,
        "session_entries": session_entries,
        "relay": relay,
        "tmux": tmux,
    }
    return {
        "detail": detail,
        "checks": [
            _check(
                "intern_removed_" + intern,
                not status_exists
                and not knowledge_exists
                and not runtime_exists
                and not session_entries
                and (not task_exists if task_dir else True)
                and (tmux_absent_ok if expect_tmux_absent else True),
                detail,
            ),
        ],
    }
