from __future__ import annotations

from typing import Any

# --- CI assertion domain registry specs (generated by B4.R4 migration) ---

ASSERTION_SPECS: tuple[dict[str, Any], ...] = ({'id': 'native.callback_health_probe',
  'title': 'Callback health probe',
  'description': 'relay/daemon callback 健康端点可访问并输出可诊断状态。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 47},
 {'id': 'f.daemon_group_proxy_api_consistent',
  'title': 'F daemon group proxy API consistent',
  'description': 'F_0012 verifies daemon /api/group/create, sync-disabled, delete, missing-project handling, and relay '
                 'registry mutation contracts with project-scoped resources.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 86},
 {'id': 'f.policy_env_idle_codex_auto_restart_consistent',
  'title': 'F policy env Idle Codex auto-restart consistent',
  'description': 'F_0034 verifies on an existing debug deployment that case-scoped policy/machine_config sync changes '
                 'Codex env hash with secret redaction, automatically restarts an Idle Codex session, dedupes '
                 'unchanged policy replay, and documents Working skip without creating a Working dialogue.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 87},
 {'id': 'f.daemon_intern_status_api_consistent',
  'title': 'F daemon intern status API consistent',
  'description': 'F_0035 verifies daemon /api/intern/check_online, offline, request_refresh, status_changed, and '
                 'refresh-repair contracts with mock relay/websocket/thread resources and structured error paths.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 88},
 {'id': 'f.daemon_chat_lookup_api_consistent',
  'title': 'F daemon chat lookup API consistent',
  'description': 'F_0036 verifies daemon /api/chat/lookup local registry lookup, relay fallback query scope, cache '
                 'update, empty result, and structured relay error handling without creating Feishu groups.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 89},
 {'id': 'f.daemon_reconnect_registry_policy_resync_consistent',
  'title': 'F daemon reconnect registry policy resync consistent',
  'description': 'F_0037 verifies on an existing debug deployment that single-daemon reconnect restores relay machine '
                 'registry online state, workspace/chat lookup, and daemon policy resync without restarting relay or '
                 'running package/reset/deploy/bootstrap.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 90},
 {'id': 'f.relay_admin_log_transfer_consistent',
  'title': 'F relay admin log transfer consistent',
  'description': 'F_0038 verifies relay /api/admin/request_logs, upload_logs, and log_status contracts, including '
                 'machine-scoped websocket payloads, tar.gz extraction, transfer status, and structured error paths '
                 'without real debug machines or Feishu.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 91},
 {'id': 'f.relay_readonly_admin_api_consistent',
  'title': 'F relay readonly admin API consistent',
  'description': 'F_0039 verifies relay readonly diagnostics /api/status, machines, scene, registry, online, chat '
                 'lookup/list/config, admin dashboard, and health contracts with mock registry/ws/api resources.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 92},
 {'id': 'f.daemon_status_group_list_api_consistent',
  'title': 'F daemon status group list API consistent',
  'description': 'F_0040 verifies daemon readonly diagnostics /api/status and /api/group/list contracts, including '
                 'registry_count, ws_clients, relay_connected, instance_id, project-scoped group list output, and 404 '
                 'behavior with mock registry/ws/relay resources.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 93},
 {'id': 'f.daemon_group_mode_proxy_api_consistent',
  'title': 'F daemon group mode proxy API consistent',
  'description': 'F_0041 verifies daemon /api/group/trigger_mode and /api/group/detail_mode proxy contracts, including '
                 'relay payload scope, mode validation, project-scoped registry lookup, relay disconnected/error '
                 'mapping, and source evidence.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 95},
 {'id': 'f.relay_helper_chat_create_consistent',
  'title': 'F relay helper chat create consistent',
  'description': 'F_0042 verifies relay /api/helper/chat/create contracts, including existing chat reuse, new helper '
                 'chat create payload, registry register, audit/message side effects, owner fallback, structured '
                 'errors, and source evidence.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 96},
 {'id': 'f.relay_monitor_snapshot_consistent',
  'title': 'F relay monitor snapshot consistent',
  'description': 'F_0043 verifies relay monitor /api/snapshot, /monitor dashboard/static assets, path safety, '
                 'owner/status aggregation, and source evidence without real relay/debug/Feishu.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 97},
 {'id': 'f.relay_chat_lifecycle_consistent',
  'title': 'F relay chat lifecycle consistent',
  'description': 'F_0044 verifies relay /api/chat/create and /api/chat/delete contracts, including project-scoped '
                 'reuse, exact list fallback, new chat creation, structured errors, scoped delete, helper cleanup, and '
                 'source evidence without real Feishu groups.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 98},
 {'id': 'f.relay_enterprise_bootstrap_consistent',
  'title': 'F relay enterprise bootstrap consistent',
  'description': 'F_0045 verifies relay /api/enterprise/daemon-policy and user-config contracts, including '
                 'authorization, owner identity validation, authorized Feishu credential injection, non-Feishu secret '
                 'redaction, user-config backup roundtrip, structured errors, and source evidence.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 99},
 {'id': 'f.relay_ci_synthetic_ingress_consistent',
  'title': 'F relay CI synthetic ingress consistent',
  'description': 'F_0046 verifies relay /api/ci/feishu_message and /api/ci/card_callback contracts, including default '
                 'disabled state, CI-policy enablement, visible audit messages, machine routing payloads, structured '
                 'errors, and source evidence.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 100},
 {'id': 'f.relay_chat_mode_write_api_consistent',
  'title': 'F relay chat mode write API consistent',
  'description': 'F_0047 verifies relay /api/chat/trigger_mode and /api/chat/detail_mode write contracts, including '
                 'project-scoped lookup, mode validation, daemon RPC error mapping, description sync, and source '
                 'evidence.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 101},
 {'id': 'f.relay_admin_html_shell_consistent',
  'title': 'F relay admin HTML shell consistent',
  'description': 'F_0048 verifies relay /admin serves a stable HTML shell wired to dashboard, log transfer, status '
                 'polling, codex rendering, warnings, and source evidence without real relay/debug/Feishu resources.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 102})


def _check(name: str, ok: bool, detail: dict[str, Any]) -> dict[str, Any]:
    return {"name": name, "ok": bool(ok), "detail": detail}


def _pane_pids(fingerprint: dict[str, Any]) -> list[str]:
    return [str(pid) for pid in (fingerprint.get("pane_pids") or [])]


def _session_running(fingerprint: dict[str, Any]) -> bool:
    status = fingerprint.get("session_status") if isinstance(fingerprint.get("session_status"), dict) else {}
    return status.get("running") is True


def idle_codex_policy_restart_check(
    before: dict[str, Any],
    current: dict[str, Any],
    *,
    expected_hash: str = "",
) -> dict[str, Any]:
    before_pids = _pane_pids(before)
    current_pids = _pane_pids(current)
    current_hash = str(current.get("codex_policy_env_hash") or "")
    hash_ok = not expected_hash or current_hash in {"", expected_hash}
    restarted = bool(before_pids and current_pids and current_pids != before_pids)
    running = _session_running(current)
    return _check(
        "idle_codex_policy_env_restart",
        running and restarted and hash_ok,
        {
            "before": before,
            "after": current,
            "before_pids": before_pids,
            "after_pids": current_pids,
            "expected_hash": expected_hash,
            "current_hash": current_hash,
            "running": running,
            "restarted": restarted,
            "hash_ok": hash_ok,
        },
    )


def policy_replay_no_duplicate_restart_check(
    before: dict[str, Any],
    current: dict[str, Any],
    *,
    expected_hash: str = "",
) -> dict[str, Any]:
    before_pids = _pane_pids(before)
    current_pids = _pane_pids(current)
    duplicate_restart = bool(before_pids and current_pids and current_pids != before_pids)
    return _check(
        "policy_replay_no_duplicate_restart",
        not duplicate_restart,
        {
            "before": before,
            "after": current,
            "before_pids": before_pids,
            "after_pids": current_pids,
            "expected_hash": expected_hash,
            "duplicate_restart": duplicate_restart,
        },
    )


def unchanged_policy_replay_kept_codex_session_check(
    before: dict[str, Any],
    current: dict[str, Any],
    *,
    expected_hash: str = "",
) -> dict[str, Any]:
    before_pids = _pane_pids(before)
    current_pids = _pane_pids(current)
    running = _session_running(current)
    return _check(
        "unchanged_policy_replay_kept_codex_session",
        bool(before_pids) and current_pids == before_pids and running,
        {
            "before": before,
            "after": current,
            "before_pids": before_pids,
            "after_pids": current_pids,
            "expected_hash": expected_hash,
            "running": running,
        },
    )


def daemon_connected_after_lifecycle_check(
    name: str,
    *,
    status: dict[str, Any],
    relay_online: dict[str, Any],
    before: dict[str, Any] | None = None,
    stdout_key: str,
    stdout: str,
) -> dict[str, Any]:
    nested_status = status.get("status") if isinstance(status.get("status"), dict) else {}
    return _check(
        name,
        status.get("running") is True and nested_status.get("relay_connected") is True,
        {
            **({"before": before} if before is not None else {}),
            stdout_key: stdout,
            "status": status,
            "after": status,
            "relay_online": relay_online,
        },
    )


def no_relay_restart_or_global_reset_check(
    before: dict[str, Any],
    after: dict[str, Any],
    steps: list[dict[str, Any]],
) -> dict[str, Any]:
    forbidden = []
    for step in steps:
        cmd = str(step.get("cmd") or "").lower()
        name = str(step.get("name") or "").lower()
        if "relay" in cmd and ("restart" in cmd or "stop" in cmd or "start" in cmd):
            forbidden.append({"name": name, "cmd": cmd})
        if any(marker in cmd for marker in (" package", " deploy", " bootstrap", "vsix", "install-runtime")):
            forbidden.append({"name": name, "cmd": cmd})
    before_uptime = int(before.get("uptime_seconds") or 0)
    after_uptime = int(after.get("uptime_seconds") or 0)
    return _check(
        "no_relay_restart_or_global_reset",
        not forbidden and (not before_uptime or after_uptime >= before_uptime),
        {"relay_before": before, "relay_after": after, "forbidden_steps": forbidden},
    )
