from __future__ import annotations

from pathlib import Path
import re
import shlex
from typing import Any

# --- CI assertion domain registry specs (generated by B4.R4 migration) ---

ASSERTION_SPECS: tuple[dict[str, Any], ...] = ({'id': 'native.session_running',
  'title': 'Session running',
  'description': 'session status 显示 running。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 19},
 {'id': 'native.session_restart_policy',
  'title': 'Session restart policy',
  'description': 'F 级 no-prompt Codex restart 只要求 restart 后 session/tmux running；fresh start 和 resume 都可接受。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 20},
 {'id': 'native.codex_session_id_resume',
  'title': 'Codex session id resume',
  'description': 'Codex /exit resume 和 restart 前后必须保持同一个真实 session UUID；tmux running 只能作为辅助证据。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 21},
 {'id': 'native.codex_exit_resume_hint',
  'title': 'Codex exit resume hint',
  'description': 'Codex /exit 后 tmux pane 打印 Resume this intern 提示，命令包含 project/type codex 且可执行。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 22},
 {'id': 'native.claude_intern_type_consistent',
  'title': 'Claude intern type consistent',
  'description': 'Claude intern 在 list/status/metadata/session map 中均显示 type=claude，不能退化为 Codex/Copilot。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 23},
 {'id': 'native.claude_group_type',
  'title': 'Claude group type',
  'description': 'case-scoped Feishu/relay group registry 保留 type=claude。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 24},
 {'id': 'native.claude_runtime_files',
  'title': 'Claude runtime files',
  'description': 'Claude start 后 .claude/settings.json hooks、~/.claude.json onboarding/trust、session map type 和 tmux '
                 'runtime env 均已材料化。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 25},
 {'id': 'native.claude_exit_resume_hint',
  'title': 'Claude exit resume hint',
  'description': 'Claude /exit 后 tmux pane 打印 Resume this intern 提示，命令包含 project/type claude 且可执行。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 26},
 {'id': 'native.claude_manual_resume_uuid_stable',
  'title': 'Claude manual resume uuid stable',
  'description': '执行 /exit 提示命令后必须 resume 同一个 Claude session UUID。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 27},
 {'id': 'native.claude_restart_resume_uuid',
  'title': 'Claude restart resume uuid',
  'description': 'Claude restart 必须输出 restarted via resume <uuid>，不得 fresh restart 或缺失真实 UUID。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 28},
 {'id': 'native.claude_resume_uuid_stable',
  'title': 'Claude resume uuid stable',
  'description': '连续 Claude restart 捕获的 resume UUID 必须保持一致。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 29},
 {'id': 'native.claude_session_scope_stable',
  'title': 'Claude session scope stable',
  'description': 'Claude session project/intern scope、tmux、daemon relay_connected 和 relay registry 在 start/restart '
                 '后保持稳定。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 30},
)


def _classified_check(name: str, ok: bool, classification: str, detail: dict[str, Any]) -> dict[str, Any]:
    return {"name": name, "ok": bool(ok), "classification": classification, "detail": detail}


def uuid_like(value: str) -> bool:
    return bool(re.fullmatch(
        r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        value or "",
    ))


def codex_session_id_from_text(text: str) -> str:
    patterns = (
        r"\brestarted via resume\s+([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})",
        r"\bresumed\s+([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})",
        r"\bcodex\s+.*\bresume\s+([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})",
    )
    for pattern in patterns:
        match = re.search(pattern, text or "", flags=re.IGNORECASE)
        if match:
            return match.group(1)
    return ""


def codex_session_id_available_check(label: str, evidence: dict[str, Any]) -> dict[str, Any]:
    session_id = str(evidence.get("session_id") or "")
    return {
        "session_id": session_id,
        "detail": evidence,
        "checks": [
            _classified_check(label, bool(session_id), "ci_capability_gap_session_id_discovery", evidence),
        ],
    }


def codex_restart_output_requires_resume_check(
    label: str,
    restart: dict[str, Any],
    *,
    before_session_id: str = "",
) -> dict[str, Any]:
    output = str(restart.get("output") or "") or (str(restart.get("stdout") or "") + str(restart.get("stderr") or ""))
    output_session_id = codex_session_id_from_text(output)
    fresh = "restarted fresh" in output.lower()
    detail = {
        "before_session_id": before_session_id,
        "output_session_id": output_session_id,
        "fresh_restart_reported": fresh,
        "restart_stdout": restart.get("stdout", ""),
        "restart_stderr": restart.get("stderr", ""),
        "restart_returncode": restart.get("returncode", 0),
        "restart_status": restart.get("session_status", {}),
    }
    checks = [
        _classified_check(label + "_not_fresh", not fresh, "product_bug_restart_fresh_without_session_id", detail),
        _classified_check(label + "_resume_id_present", bool(output_session_id), "product_bug_restart_missing_resume_session_id", detail),
    ]
    if before_session_id:
        checks.append(_classified_check(
            label + "_same_id",
            output_session_id == before_session_id,
            "product_bug_restart_loses_session_id",
            detail,
        ))
    return {"detail": detail | {"restart_policy": "resume_with_same_session_id"}, "checks": checks}


def codex_restart_output_allows_fresh_start_check(label: str, restart: dict[str, Any]) -> dict[str, Any]:
    output = str(restart.get("output") or "") or (str(restart.get("stdout") or "") + str(restart.get("stderr") or ""))
    output_session_id = codex_session_id_from_text(output)
    reported_resume = bool(restart.get("reported_resume")) or "restarted via resume" in output.lower()
    reported_fresh = bool(restart.get("reported_fresh")) or "restarted fresh" in output.lower()
    status = restart.get("session_status") if isinstance(restart.get("session_status"), dict) else {}
    detail = {
        "output_session_id": output_session_id,
        "reported_resume": reported_resume,
        "reported_fresh": reported_fresh,
        "restart_stdout": restart.get("stdout", ""),
        "restart_stderr": restart.get("stderr", ""),
        "restart_returncode": restart.get("returncode", 0),
        "restart_status": status,
    }
    return {
        "detail": detail | {"restart_policy": "fresh_or_resume_startup_ok"},
        "checks": [
            _classified_check(
                label + "_accepted_start_mode",
                reported_resume or reported_fresh or output.strip().endswith(": restarted"),
                "product_bug_restart_output_unrecognized",
                detail,
            ),
        ],
    }


def codex_session_id_equal_checks(
    label: str,
    before_evidence: dict[str, Any],
    after_evidence: dict[str, Any],
) -> dict[str, Any]:
    before_id = str(before_evidence.get("session_id") or "")
    after_id = str(after_evidence.get("session_id") or "")
    detail = {
        "before": before_evidence,
        "after": after_evidence,
        "before_session_id": before_id,
        "after_session_id": after_id,
    }
    return {
        "before_session_id": before_id,
        "after_session_id": after_id,
        "detail": detail | {"same_session_id": True},
        "checks": [
            _classified_check(label + "_before_available", bool(before_id), "ci_capability_gap_session_id_discovery", before_evidence),
            _classified_check(label + "_after_available", bool(after_id), "ci_capability_gap_session_id_discovery", after_evidence),
            _classified_check(label + "_same_id", before_id == after_id, "product_bug_restart_loses_session_id", detail),
        ],
    }


def resume_hint_command_contract_check(
    label: str,
    command: str,
    *,
    workspace: dict[str, Any],
    intern: str,
    session_type: str,
) -> dict[str, Any]:
    try:
        tokens = shlex.split(command)
    except ValueError as exc:
        tokens = []
        split_error = str(exc)
    else:
        split_error = ""
    project = str(workspace.get("display") or "")
    internctl_tokens = [token for token in tokens if Path(token).name in {"internctl", "internctl.py"}]
    has_project = "--project" in tokens and tokens.index("--project") + 1 < len(tokens) and tokens[tokens.index("--project") + 1] == project
    has_type = "--type" in tokens and tokens.index("--type") + 1 < len(tokens) and tokens[tokens.index("--type") + 1] == session_type
    has_resume = "session" in tokens and "resume" in tokens and intern in tokens
    detail = {
        "command": command,
        "tokens": tokens,
        "split_error": split_error,
        "expected_project": project,
        "expected_intern": intern,
        "expected_type": session_type,
        "has_internctl": bool(internctl_tokens),
        "has_resume": has_resume,
        "has_project": has_project,
        "has_type": has_type,
    }
    return {
        "detail": detail | {"valid": True},
        "checks": [
            _classified_check(
                label,
                bool(tokens) and not split_error and bool(internctl_tokens) and has_resume and has_project and has_type,
                "product_bug_exit_resume_hint_command_invalid",
                detail,
            ),
        ],
    }
