from __future__ import annotations

import re
from typing import Any

# --- CI assertion domain registry specs (generated by B4.R4 migration) ---

ASSERTION_SPECS: tuple[dict[str, Any], ...] = ({'id': 'f.artifact_index_complete',
  'title': 'F artifact index complete',
  'description': 'F_0012 verifies debug diagnostics collect stdout/stderr, daemon, relay, tmux, git, report artifacts '
                 'with safe paths and redaction.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 68},
 {'id': 'f.report_export_schema',
  'title': 'F report export schema',
  'description': 'F_0013 verifies report/dashboard export schema, summary counts, failure links, and reload '
                 'compatibility.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 69},
 {'id': 'f.secret_redaction_complete',
  'title': 'F secret redaction complete',
  'description': 'F_0014 verifies report, artifact, dashboard, app secret, repo token, and SSH key redaction while '
                 'retaining diagnostic fields.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 70},
 {'id': 'f.metadata_migration_idempotent',
  'title': 'F metadata migration idempotent',
  'description': 'F_0015 verifies legacy metadata migration, idempotent reruns, interrupted migration diagnostics, and '
                 'line-3 metadata preservation.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 71},
 {'id': 'f.config_cli_state_exact',
  'title': 'F config CLI state exact',
  'description': 'F_0023 verifies format-check and Codex load-balance config toggles, exact JSON state, TOML '
                 'preservation, and no mutation on load-balance ping failure.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
                 'notes': [],
                 'order': 73})


def _compact_js(text: str) -> str:
    return re.sub(r"\s+", "", text).replace("'", '"')


def _dist_contract_result(checks: list[tuple[str, bool]], *, bundle: str = "") -> dict[str, Any]:
    results = [{"name": name, "ok": bool(ok), "detail": {}} for name, ok in checks]
    contract = {
        "checks": results,
        "ok": all(item["ok"] for item in results),
        "failed": [item["name"] for item in results if not item["ok"]],
    }
    if bundle:
        contract["bundle"] = bundle
    return contract


def applied_contract_checks(contract: dict[str, Any]) -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []
    for check in contract.get("checks") or []:
        if not isinstance(check, dict):
            continue
        checks.append({
            "name": str(check.get("name") or ""),
            "ok": bool(check.get("ok")),
            "detail": dict(check.get("detail") or {}),
        })
    return checks


def require_deployed_contract(case: Any, contract_id: str, artifact_key: str) -> dict[str, Any]:
    contract = case.ctx.action.source_contract.deployed_contract_remote(contract_id)
    for check in applied_contract_checks(contract):
        case.require(check["name"], check["ok"], check["detail"])
    case.artifacts[artifact_key] = contract
    return contract


def task_treeview_projection_dist_contract(dist: str, *, bundle: str = "") -> dict[str, Any]:
    compact = _compact_js(dist)
    task_match = re.search(r"case\s*['\"]task['\"]", dist)
    task_start = task_match.start() if task_match else -1
    intern_group_match = re.search(r"case\s*['\"]intern-group['\"]", dist[task_start:] if task_start >= 0 else "")
    intern_group_start = task_start + intern_group_match.start() if task_start >= 0 and intern_group_match else -1
    task_block = dist[task_start:intern_group_start] if task_start >= 0 and intern_group_start > task_start else dist
    task_compact = _compact_js(task_block)
    open_readme_start = dist.find("tree.openTaskReadme")
    if open_readme_start >= 0:
        group_block = dist[max(0, open_readme_start - 1500):open_readme_start + 1500]
    else:
        group_match = re.search(r"['\"]task-group['\"]\s*===|===\s*['\"]task-group['\"]|taskGroupItems\.map|taskGroupItems", dist)
        group_start = group_match.start() if group_match else -1
        group_block = dist[group_start:group_start + 2500] if group_start >= 0 else dist
    readme_open_contract = (
        "existsSync" in dist
        and "vscode.open" in dist
        and "readmePath" in dist
        and "tree.openTaskReadme" in dist
    )
    readme_path_contract = "readmePath" in dist and "README.md" in dist and "metadataRootForProject" in dist
    group_compact = _compact_js(group_block)
    optional_task_command = (
        "vscode.open" in group_block
        and ("undefined" in group_block or "void 0" in group_block or "void0" in group_compact)
    ) or (readme_open_contract and "void0" in compact)
    inprogress_pr_guard = bool(re.search(
        r"(?:['\"]InProgress['\"]===[A-Za-z_$][\w$]*\.status|[A-Za-z_$][\w$]*\.status===['\"]InProgress['\"])&&[A-Za-z_$][\w$]*\.pr",
        task_compact,
    ))
    return _dist_contract_result([
        ("f0023_bundle_has_task_tree_item", "taskInfo" in dist and "tree.task.tooltip" in dist),
        ("f0023_inprogress_description_formats_pr", "PR#" in task_block and "InProgress" in task_block and "merge_requests" in task_block),
        ("f0023_tooltip_keeps_raw_pr", "tree.task.tooltip" in task_block and "PR:" in task_block),
        ("f0023_readme_open_requires_existing_file", readme_open_contract),
        ("f0023_readme_open_uses_task_readme_path", readme_path_contract),
        ("f0023_task_groups_use_expected_statuses", "InProgress" in dist and "Open" in dist and "Completed" in dist),
        ("f0023_task_node_command_is_optional", optional_task_command),
        ("f0023_non_inprogress_tasks_do_not_format_pr", "InProgress" in task_block and "PR#" in task_block and inprogress_pr_guard),
    ], bundle=bundle)


def task_delete_gui_dist_contract(dist: str, *, bundle: str = "") -> dict[str, Any]:
    compact = _compact_js(dist)
    return _dist_contract_result([
        ("f0024_bundle_has_delete_task_command", 'registerCommand("intern.deleteTask"' in compact and "handleDeleteTaskCommand" in dist),
        ("f0024_quickpick_uses_enabled_project_tasks", "getEnabledProjects" in dist and "getTasksWithMetadata" in dist and "showQuickPick" in dist),
        ("f0024_no_task_warning_before_quickpick", "appState.warn.noTaskToDelete" in dist),
        ("f0024_inprogress_guard_before_cli", "appState.warn.taskInProgress" in dist and "task-delete" in dist),
        ("f0024_confirm_modal_before_cli", "appState.confirm.deleteTask" in dist and "showWarningMessage" in dist and "task-delete" in dist),
        ("f0024_delete_maps_to_internal_task_delete", '"internal","task-delete"' in compact and '"--confirm","--json"' in compact),
        ("f0024_success_reports_branch_commit_fallback", "branches" in dist and "commits" in dist and "CLI" in dist and "showInformationMessage" in dist),
        ("f0024_failure_shows_error_message", "showErrorMessage" in dist),
    ], bundle=bundle)


def workspace_disable_delete_gui_dist_contract(dist: str, *, bundle: str = "") -> dict[str, Any]:
    compact = _compact_js(dist)
    remove_start = dist.find("removeWorkspaceWithCleanup")
    stop_start = dist.find("stopMaintainingProject")
    enabled_start = dist.find("getEnabledProjects")
    remove_block = dist[remove_start:stop_start] if remove_start >= 0 and stop_start > remove_start else ""
    stop_block = dist[stop_start:enabled_start] if stop_start >= 0 and enabled_start > stop_start else ""
    remove_compact = _compact_js(remove_block)
    stop_compact = _compact_js(stop_block)
    return _dist_contract_result([
        ("f0021_bundle_has_remove_handler_registration", 'registerCommand("intern.removeWorkspace"' in compact and "handleRemoveWorkspaceCommand" in dist),
        ("f0021_bundle_has_stop_handler_registration", 'registerCommand("intern.stopMaintainProject"' in compact and "handleStopMaintainProjectCommand" in dist),
        ("f0021_remove_core_guard_precedes_cli", "axis_intern_agents" in remove_block and remove_block.find("axis_intern_agents") < remove_block.find("runInternctl")),
        ("f0021_remove_modal_precedes_cli", "showWarningMessage" in remove_block and remove_block.find("showWarningMessage") < remove_block.find("runInternctl")),
        ("f0021_remove_uses_workspace_disable", 'runInternctl(["workspace","disable"' in remove_compact),
        ("f0021_remove_does_not_use_workspace_delete", '["workspace","delete"' not in remove_compact),
        ("f0021_stop_typed_confirm_precedes_cli", "showInputBox" in stop_block and stop_block.find("showInputBox") < stop_block.find("runInternctl")),
        ("f0021_stop_uses_workspace_delete_confirm", 'runInternctl(["workspace","delete"' in stop_compact and '"--confirm","--json"' in stop_compact),
    ], bundle=bundle)


def workspace_enable_doctor_refresh_dist_contract(dist: str, *, bundle: str = "") -> dict[str, Any]:
    compact = _compact_js(dist)
    refresh_start = min(
        [
            index for index in (
                dist.find('registerCommand("intern.refreshTree"'),
                dist.find("registerCommand('intern.refreshTree'"),
            )
            if index >= 0
        ],
        default=-1,
    )
    refresh_end = min(
        [
            index for index in (
                dist.find('registerCommand("intern-agent.toggleFormatCheck"', refresh_start),
                dist.find("registerCommand('intern-agent.toggleFormatCheck'", refresh_start),
            )
            if index >= 0
        ],
        default=-1,
    )
    refresh_block = dist[refresh_start:refresh_end] if refresh_start >= 0 and refresh_end > refresh_start else ""
    return _dist_contract_result([
        ("f0022_bundle_has_refresh_command", bool(refresh_block)),
        ("f0022_refresh_syncs_metadata_and_loads_interns", "syncProjectMetadata" in refresh_block and "loadInterns" in refresh_block and "loadInternTypes" in refresh_block),
        ("f0022_refresh_reports_sync_failure", "Refresh failed" in refresh_block and "showErrorMessage" in refresh_block),
        ("f0022_refresh_preserves_last_good_before_refresh", "showErrorMessage" in refresh_block and ".refresh()" in refresh_block and refresh_block.find("showErrorMessage") < refresh_block.find(".refresh()")),
        ("f0022_workspace_list_and_task_list_sources_present", 'runInternctl(["workspace","list","--json"])' in compact and '"internal","task-list"' in compact),
        ("f0022_enabled_projects_filter_exists", "getEnabledProjects(){returnthis.config.projects.filter" in compact),
        ("f0022_tree_uses_workspace_projection_inputs", "getTasksForProject" in dist and "skillSourcesRootForProject" in dist and "workspaceName" in dist),
    ], bundle=bundle)


def skill_source_treeview_dist_contract(dist: str, *, bundle: str = "") -> dict[str, Any]:
    compact = _compact_js(dist)
    return _dist_contract_result([
        ("f0029_bundle_has_skill_project_and_pkg_context", "skill-project" in dist and "skill-pkg" in dist),
        ("f0029_bundle_has_disabled_skill_context", "skill-item-catalog-disabled" in dist),
        ("f0029_bundle_opens_skill_md", "vscode.open" in dist and "skillMdPath" in dist),
        ("f0029_bundle_registers_add_source", 'registerCommand("intern.skill.addSource"' in compact and "skill.add.fromGit" in dist and "skill.add.fromLocal" in dist),
        ("f0029_bundle_update_pkg_maps_to_update_source", 'registerCommand("intern.skill.tree.updatePkg"' in compact and '"skill","update-source","--project"' in compact),
        ("f0029_bundle_remove_pkg_confirms_and_maps_to_remove_source", 'registerCommand("intern.skill.tree.removePkg"' in compact and "skill.source.confirmRemoveCascade" in dist and '"skill","remove-source","--project"' in compact),
    ], bundle=bundle)


def codex_skill_scope_dist_contract(dist: str, *, bundle: str = "") -> dict[str, Any]:
    compact = _compact_js(dist)
    enable_personal_start = dist.find('registerCommand("intern.skill.tree.enablePersonal"')
    disable_repo_start = dist.find('registerCommand("intern.skill.tree.disableRepo"', enable_personal_start)
    enable_personal_block = dist[enable_personal_start:disable_repo_start] if enable_personal_start >= 0 and disable_repo_start > enable_personal_start else ""
    contract = _dist_contract_result([
        ("f0030_bundle_registers_enable_repo", 'registerCommand("intern.skill.tree.enableRepo"' in compact and "skill.repo.confirmEnableProjectWide" in dist),
        ("f0030_bundle_repo_enable_maps_to_skill_enable", '"skill","enable","--project"' in compact and "skill.add.progressTitle" in dist),
        ("f0030_bundle_repo_personal_reject_present", bool(enable_personal_block) and "skill.enable.rejectPersonalDueToRepo" in enable_personal_block and "personal_enabled.includes" in enable_personal_block),
        ("f0030_bundle_promote_personal_present", "skill.action.promoteFromPersonal" in dist and "--promote-personal" in dist),
        ("f0030_bundle_disable_repo_and_personal_present", 'registerCommand("intern.skill.tree.disableRepo"' in compact and 'registerCommand("intern.skill.tree.disablePersonal"' in compact),
    ], bundle=bundle)
    contract["enable_personal_block_tail"] = _compact_js(enable_personal_block)[:800]
    return contract


def treeview_top_level_config_status_dist_contract(dist: str, *, bundle: str = "") -> dict[str, Any]:
    compact = _compact_js(dist)
    refresh_start = dist.find("intern.refreshTree")
    toggle_start = dist.find("intern-agent.toggleFormatCheck")
    refresh_block = dist[refresh_start:toggle_start] if refresh_start >= 0 and toggle_start > refresh_start else dist
    refresh_compact = _compact_js(refresh_block)
    refresh_failure = refresh_block.find("Refresh failed:")
    refresh_after_failure = refresh_block.find(".refresh()", refresh_failure if refresh_failure >= 0 else 0)
    refresh_failure_returns_before_refresh = (
        refresh_failure >= 0
        and "return" in refresh_block[:refresh_failure]
        and refresh_after_failure > refresh_failure
    )
    status_start = dist.find("createStatusBarItem")
    status_end = dist.find("ext.activate.checkDone", status_start)
    status_block = dist[status_start:status_end] if status_start >= 0 and status_end > status_start else ""
    contract = _dist_contract_result([
        ("f0031_bundle_has_plugin_meta_and_config", "Intern Agent Helper v" in dist and "Build:" in dist and "Extension:" in dist and "Install:" in dist and "tree.config.projects" in dist),
        ("f0031_bundle_registers_format_toggle", 'registerCommand("intern-agent.toggleFormatCheck"' in compact and '"config","format-check","toggle","--json"' in compact),
        ("f0031_bundle_format_toggle_reports_errors", "internctl config format-check failed" in dist and "showErrorMessage" in dist),
        ("f0031_bundle_language_switch_reload_contract", 'registerCommand("intern.switchLanguage"' in compact and "workbench.action.reloadWindow" in dist and "cmd.switchLanguage.reloadNow" in dist and "cmd.switchLanguage.later" in dist),
        ("f0031_bundle_refresh_failure_returns_before_refresh", refresh_failure_returns_before_refresh),
        ("f0031_bundle_statusbar_health_markers", bool(status_block) and "isDaemonReachable" in status_block and "getDaemonStatus" in status_block and "relay_connected" in status_block and "statusBarItem.warningBackground" in status_block),
        ("f0031_bundle_does_not_require_setup_execution", "intern.setupRefresh" in dist and "intern.setupAutoFix" in dist),
    ], bundle=bundle)
    contract["refresh_block_compact_tail"] = refresh_compact[:800]
    contract["status_block_compact_tail"] = _compact_js(status_block)[:800]
    return contract


def treeview_menu_visibility_dist_contract(dist: str, *, bundle: str = "") -> dict[str, Any]:
    compact = _compact_js(dist)
    project_scope_guard = bool(re.search(r"typeof[A-Za-z_$][\w$]*\.project", compact))
    return _dist_contract_result([
        ("f0032_bundle_has_codex_workspace_task_skill_contexts", "intern-codex" in dist and "skill-project" in dist and "skill-pkg" in dist and "task" in dist),
        ("f0032_bundle_has_skill_context_values", "skill-item-catalog-disabled" in dist and "skill-item-catalog-enabled-repo" in dist and "skill-item-enabled-personal" in dist),
        ("f0032_bundle_codex_session_handlers_are_treeitem_scoped", "pickInternFromContext" in dist and project_scope_guard and 'registerCommand("intern.createCodexSession"' in compact),
        ("f0032_bundle_delete_task_handler_registered", 'registerCommand("intern.deleteTask"' in compact),
    ], bundle=bundle)


def _dist_command_block(dist: str, command: str, *, window: int = 5000) -> str:
    start = dist.find(command)
    if start < 0:
        return ""
    next_match = re.search(r"registerCommand\(\s*['\"]intern\.", dist[start + len(command):])
    if next_match:
        end = start + len(command) + next_match.start()
        return dist[start:end]
    return dist[start:start + window]


def claude_treeview_command_dist_contract(
    dist: str,
    claude_rows: list[dict[str, str]],
    *,
    bundle: str = "",
    package_path: str = "",
) -> dict[str, Any]:
    compact = _compact_js(dist)
    claude_visible = [row["command"] for row in claude_rows]
    create_block = _dist_command_block(dist, "intern.createClaudeSession")
    restart_block = _dist_command_block(dist, "intern.restartClaudeSession")
    start_block = _dist_command_block(dist, "startCliTmuxSession", window=6500)
    restart_cli_block = _dist_command_block(dist, "sessionRestartCommand", window=4500) + _dist_command_block(dist, "runSessionRestart", window=4500)
    ensure_claude_block = _dist_command_block(dist, "ensureClaudeTmuxTerminal", window=6500)
    create_compact = _compact_js(create_block + ensure_claude_block + start_block)
    restart_compact = _compact_js(restart_block + restart_cli_block)
    required_menu = {
        "intern.openChatForIntern",
        "intern.createClaudeSession",
        "intern.restartClaudeSession",
        "intern.deleteIntern",
        "intern.forceDeleteIntern",
        "intern.setTriggerModeAll",
        "intern.setTriggerModeAtOnly",
        "intern.setDetailModeFull",
        "intern.setDetailModeSummary",
    }
    menu_missing = sorted(required_menu - set(claude_visible))
    codex_env_markers = [
        marker for marker in ("CODEX_RESUME_ON_START", "--resume-last", "resumeLast")
        if marker in (create_block + ensure_claude_block + start_block + restart_cli_block)
    ]
    contract = _dist_contract_result([
        ("f0044_bundle_has_claude_context_value", "intern-claude" in dist and "team-coordinator-claude" in dist),
        ("f0044_bundle_has_claude_terminal_icon", "terminal" in dist and "claude" in dist.lower()),
        ("f0044_package_menu_has_claude_commands", not menu_missing),
        ("f0044_create_claude_registered", 'registerCommand("intern.createClaudeSession"' in compact),
        ("f0044_create_claude_uses_session_start", '"session","start"' in create_compact and '"--type"' in create_compact and '"claude"' in create_compact and '"--no-attach"' in create_compact),
        ("f0044_restart_claude_registered", 'registerCommand("intern.restartClaudeSession"' in compact),
        ("f0044_restart_claude_uses_session_restart", '"session","restart"' in restart_compact and '"--type"' in restart_compact and '"claude"' in restart_compact and '"--no-attach"' in restart_compact),
        ("f0044_claude_command_has_no_codex_env_or_resume", not codex_env_markers),
        ("f0044_claude_menu_not_team_only", "intern-claude" in " ".join(row["when"] for row in claude_rows)),
    ], bundle=bundle)
    contract.update({
        "package": package_path,
        "claude_menu_rows": claude_rows,
        "claude_visible_commands": claude_visible,
        "menu_missing": menu_missing,
        "codex_env_markers": codex_env_markers,
        "create_block_tail": _compact_js(create_block + ensure_claude_block + start_block)[:1200],
        "restart_block_tail": _compact_js(restart_block + restart_cli_block)[:1200],
        "team_context_rows": [row for row in claude_rows if "team-coordinator-claude" in row["when"]],
    })
    return contract


def claude_skill_group_source_contract(
    dist: str,
    *,
    skill_text: str,
    skill_cli_source: dict[str, Any],
    claude_group_rows: list[dict[str, str]],
    skill_disabled: list[dict[str, str]],
    skill_repo: list[dict[str, str]],
    skill_personal: list[dict[str, str]],
    bundle: str = "",
) -> dict[str, Any]:
    compact = _compact_js(dist)
    required_group = {
        "intern.setTriggerModeAll",
        "intern.setTriggerModeAtOnly",
        "intern.setDetailModeFull",
        "intern.setDetailModeSummary",
    }
    visible_group = {row["command"] for row in claude_group_rows}
    contract = _dist_contract_result([
        ("f0045_cli_skill_declares_claude_farm", ".claude/skills" in skill_text and "CLAUDE_FARM_REL" in skill_text),
        ("f0045_cli_skill_preserves_codex_farm", ".agents/skills" in skill_text and "CODEX_FARM_REL" in skill_text),
        ("f0045_cli_skill_type_drives_farm", "farm_rel_for_type" in skill_text and "get_intern_type" in skill_text and "skill_sync" in skill_text),
        ("f0045_bundle_skill_tree_commands_registered", all(marker in compact for marker in (
            'registerCommand("intern.skill.tree.enableRepo"',
            'registerCommand("intern.skill.tree.enablePersonal"',
            'registerCommand("intern.skill.tree.disableRepo"',
            'registerCommand("intern.skill.tree.disablePersonal"',
        ))),
        ("f0045_package_skill_menus_visible", bool(skill_disabled and skill_repo and skill_personal)),
        ("f0045_claude_group_menu_commands_visible", required_group.issubset(visible_group)),
        ("f0045_group_commands_are_project_scoped_source", "runGroupModeCli" in dist and "--project" in dist and "pickInternFromContext" in dist),
    ], bundle=bundle)
    contract.update({
        "skill_cli_source": skill_cli_source,
        "claude_group_rows": claude_group_rows,
        "skill_rows": {
            "disabled": skill_disabled,
            "repo": skill_repo,
            "personal": skill_personal,
        },
        "group_visible_commands": sorted(visible_group),
        "group_missing": sorted(required_group - visible_group),
    })
    return contract
