from __future__ import annotations

from typing import Any

# --- CI assertion domain registry specs (generated by B4.R4 migration) ---

ASSERTION_SPECS: tuple[dict[str, Any], ...] = ({'id': 'native.hook_context_guard',
  'title': 'Hook context guard',
  'description': 'hook stdout、additionalContext 片段判定和 state before/after artifact 满足上下文保护约束。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 53},
 {'id': 'f.gui_command_coverage_complete',
  'title': 'F GUI command coverage complete',
  'description': 'F_0011 verifies contributed non-setup VS Code commands have registry, handler, CLI equivalent or '
                 'unit-test evidence, and stable covered/deferred/excluded classification.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 65},
 {'id': 'f.skill_sync_state_consistent',
  'title': 'F skill sync state consistent',
  'description': 'F_0016 verifies product skill CLI add-skill source registry, GUI add-skill mapping, list output, '
                 'repo enable state, sync payload, update idempotency, disable/remove, and cleanup.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 72},
 {'id': 'f.vscode_treeview_current_gui_consistent',
  'title': 'F VS Code TreeView current GUI consistent',
  'description': 'F_0028 verifies current non-setup TreeView workspace, intern, Codex session, task, and navigation '
                 'controls through focused local Jest fixtures.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 78},
 {'id': 'f.group_mode_cli_gui_consistent',
  'title': 'F group mode CLI/GUI consistent',
  'description': 'F_0031 verifies internctl group trigger/detail mode daemon payloads, JSON error reports, '
                 'daemon-unavailable diagnostics, VS Code GUI command handler evidence, and relay /trigger_mode, '
                 '/detail_mode, /config local fixtures without creating a real Feishu group.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 83},
 {'id': 'f.helper_control_cli_slash_consistent',
  'title': 'F helper control CLI/slash consistent',
  'description': 'F_0032 verifies internctl helper start/status/stop/invite-owner payloads, JSON error reports, '
                 'daemon-unavailable diagnostics, and /helper slash source evidence without creating real helper '
                 'groups.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 84},
 {'id': 'f.main_bot_control_surface_consistent',
  'title': 'F main bot control surface consistent',
  'description': 'F_0033 verifies main bot P2P /status, /debug, /list, unsupported create/add rejection, help '
                 'fallback, and group-chat non-spam guard without creating Feishu groups.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 85},
 {'id': 'f.skill_source_treeview_projection_consistent',
  'title': 'F skill source TreeView projection consistent',
  'description': 'F_0029 verifies on an existing debug deployment that Skill Sources TreeView '
                 'add/project/open/update/remove/invalid rollback contracts remain consistent using deployed internctl '
                 'skill side effects and deployed extension bundle evidence.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 106},
 {'id': 'f.codex_skill_scope_sync_consistent',
  'title': 'F Codex skill scope sync consistent',
  'description': 'F_0030 verifies on an existing debug deployment that Codex-only repo and personal skill '
                 'enable/disable/promote scope, farm sync, duplicate no-op, repo-enabled personal reject GUI contract, '
                 'and no non-Codex/Copilot shared state remain consistent.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 107},
 {'id': 'f.treeview_top_level_config_status_consistent',
  'title': 'F TreeView top-level config/status consistent',
  'description': 'F_0031 verifies on an existing debug deployment that plugin meta/config items, format-check toggle '
                 'CLI mapping and failure feedback, language switch reload prompt, refreshTree last-good behavior, and '
                 'plugin status bar health hints remain consistent.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 108},
 {'id': 'f.treeview_menu_visibility_context_consistent',
  'title': 'F TreeView menu visibility/context consistent',
  'description': 'F_0032 verifies on an existing debug deployment that Codex/workspace/task/skill TreeItem '
                 'contextValue and package.json menu when-contracts, command palette hiding, project-scoped action '
                 'registry evidence, and no Team/Setup/Copilot shared command execution remain consistent.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 109},
 {'id': 'f.claude_treeview_command_parity_consistent',
  'title': 'F Claude TreeView command parity consistent',
  'description': 'F_0044 verifies on an existing debug deployment that Claude intern TreeView projection, project '
                 'scope, no-prompt online fixture behavior, package menus, and create/restart Claude CLI wrapper '
                 'source contracts remain consistent.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 110},
 {'id': 'f.claude_skill_farm_group_parity_consistent',
  'title': 'F Claude skill farm/group parity consistent',
  'description': 'F_0045 verifies on an existing debug deployment that Claude repo/personal skill sync uses '
                 '.claude/skills, does not write Codex .agents/skills, keeps projection/config counts consistent, and '
                 'supports project-scoped group trigger/detail mode parity without Team or agent prompts.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
                 'notes': [],
                 'order': 111})


def _check(name: str, ok: bool, detail: dict[str, Any]) -> dict[str, Any]:
    return {"name": name, "ok": bool(ok), "detail": detail}


def intern_list_single_match_check(intern: str, *, count: int, matches: Any, items: Any) -> dict[str, Any]:
    return _check(
        "intern_list_single_match_" + intern,
        count == 1,
        {"matches": matches or [], "items": items or []},
    )


def checked_item_projection(case: Any, workspace: dict[str, Any], intern: str, *, focus_intern: str = "") -> dict[str, Any]:
    projection = case.ctx.action.treeview.item_projection_remote(
        workspace,
        intern,
        focus_intern=focus_intern,
    )
    check = intern_list_single_match_check(
        intern,
        count=int(projection.get("list_match_count") or 0),
        matches=projection.get("list_matches") or [],
        items=projection.get("list_items") or [],
    )
    case.require(check["name"], check["ok"], check["detail"])
    return projection


def checked_workspace_projection(
    case: Any,
    workspace: dict[str, Any],
    interns: list[str],
    *,
    focus_intern: str = "",
) -> dict[str, Any]:
    tree = case.ctx.action.treeview.workspace_projection_remote(
        workspace,
        interns,
        focus_intern=focus_intern,
    )
    for item in tree.get("items") or []:
        intern = str(item.get("name") or "")
        if not intern:
            continue
        check = intern_list_single_match_check(
            intern,
            count=int(item.get("list_match_count") or 0),
            matches=item.get("list_matches") or [],
            items=item.get("list_items") or [],
        )
        case.require(check["name"], check["ok"], check["detail"])
    return tree


def view_item_command_rows(package: dict[str, Any], view_item: str) -> list[dict[str, str]]:
    menus = package.get("contributes", {}).get("menus", {})
    entries = menus.get("view/item/context", []) if isinstance(menus, dict) else []
    marker = f"viewItem == {view_item}"
    rows: list[dict[str, str]] = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        when = str(entry.get("when") or "")
        if marker not in when:
            continue
        rows.append({
            "command": str(entry.get("command") or ""),
            "when": when,
            "group": str(entry.get("group") or ""),
        })
    return rows


def deployed_menu_commands_check(
    package: dict[str, Any],
    view_item: str,
    includes: tuple[str, ...],
) -> dict[str, Any]:
    rows = view_item_command_rows(package, view_item)
    visible = [row["command"] for row in rows]
    missing = [command for command in includes if command not in visible]
    detail = {
        "view_item": view_item,
        "required": list(includes),
        "visible": visible,
        "rows": rows,
        "missing": missing,
    }
    return _check("deployed_menu_" + view_item.replace("-", "_"), not missing, detail)


def command_palette_hidden_check(package: dict[str, Any], commands: tuple[str, ...]) -> dict[str, Any]:
    menus = package.get("contributes", {}).get("menus", {})
    entries = menus.get("commandPalette", []) if isinstance(menus, dict) else []
    hidden = {
        str(entry.get("command") or "")
        for entry in entries
        if isinstance(entry, dict) and str(entry.get("when") or "") == "false"
    }
    missing = [command for command in commands if command not in hidden]
    return _check(
        "deployed_command_palette_hidden",
        not missing,
        {"required": list(commands), "hidden": sorted(hidden), "missing": missing},
    )
