from __future__ import annotations

from pathlib import Path
from typing import Any

# --- CI assertion domain registry specs (generated by B4.R4 migration) ---

ASSERTION_SPECS: tuple[dict[str, Any], ...] = ({'id': 'native.workspace_id_present',
  'title': 'Workspace id present',
  'description': 'workspace create 返回可解析 workspace id。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 12},
 {'id': 'native.metadata_resolves_role',
  'title': 'Metadata resolves role',
  'description': 'metadata resolver 对指定 role 返回 ok。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 13},
 {'id': 'native.repo_mode_resource_matrix',
  'title': 'Repo mode resource matrix',
  'description': 'Codeup/GitHub x repo_dotdir/metadata_branch/local_only checkout 与 metadata root 均符合 mode 契约。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 37},
 {'id': 'native.protected_repo_push_guard',
  'title': 'Protected repo push guard',
  'description': '受保护 Codeup repo 的 repo_dotdir direct metadata write 被拒绝并给出安全替代路径。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 38},
 {'id': 'native.workspace_delete_ok',
  'title': 'Workspace delete ok',
  'description': 'workspace delete 返回成功并完成清理。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 48},
 {'id': 'native.workspace_gui_cli_equivalent',
  'title': 'Workspace GUI/CLI equivalent',
  'description': 'workspace GUI add/remove/mode script 使用可审计的 internctl CLI 等价路径执行。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 54},
 {'id': 'native.workspace_record',
  'title': 'Workspace record',
  'description': 'daemon/relay workspace registry 记录 provider、mode、repo_url/path 和 display name 与用户输入一致。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 55},
 {'id': 'native.workspace_metadata_root',
  'title': 'Workspace metadata root',
  'description': 'repo_dotdir、metadata_branch、local_only 的 metadata root/checkout 路径符合 workspace mode contract。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 56},
 {'id': 'native.relay_workspace_sync',
  'title': 'Relay workspace sync',
  'description': 'daemon workspace registry 与 relay /api/workspaces 对目标 workspace 的可见状态一致。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 57},
 {'id': 'native.workspace_removed',
  'title': 'Workspace removed',
  'description': 'workspace delete 后 daemon 本机 registry 和 relay registry 均不再返回该 display name。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 58},
 {'id': 'native.workspace_disabled',
  'title': 'Workspace disabled',
  'description': 'local_only workspace remove 后本机 registry 保留定义但 local enabled 状态关闭，且不要求 relay/global delete。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 58},
 {'id': 'native.metadata_branch_created',
  'title': 'Metadata branch created',
  'description': 'metadata_branch workspace 能定位 metadata checkout/branch，并且不会误写 repo_dotdir metadata root。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 59},
 {'id': 'native.business_branch_unchanged',
  'title': 'Business branch unchanged',
  'description': 'workspace add/delete 前后业务默认分支 revision 保持不变。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 60},
 {'id': 'native.workspace_create_failed_rollback',
  'title': 'Workspace create failed rollback',
  'description': 'duplicate/invalid workspace create 返回可分类失败，且不留下半成品 registry、metadata 或 relay record。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 61},
 {'id': 'native.local_repo_preserved',
  'title': 'Local repo preserved',
  'description': '删除 local workspace 只移除 workspace registry，不删除用户本地 git repo 内容。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 62},
 {'id': 'native.no_remote_credentials_used',
  'title': 'No remote credentials used',
  'description': 'local_only workspace add/delete 不读取或发送 Codeup/GitHub 远端凭据。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 63},
 {'id': 'native.workspace_mode_switch_contract',
  'title': 'Workspace mode switch contract',
  'description': 'remote repo_dotdir/metadata_branch 可双向切换，local_only 相关转换被拒绝且失败后状态不变。',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 64},
 {'id': 'f.workspace_disable_delete_gui_consistent',
  'title': 'F workspace disable/delete GUI consistent',
  'description': 'F_0021 verifies on an existing debug deployment that Remove Workspace maps to workspace disable, '
                 'Stop Maintaining Project maps to workspace delete --confirm, cancel/mismatch/core guards do not '
                 'invoke destructive CLI, and workspace repo content is preserved.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 66},
 {'id': 'f.workspace_enable_doctor_refresh_consistent',
  'title': 'F workspace enable/doctor/refresh consistent',
  'description': 'F_0022 verifies on an existing debug deployment that disabled workspace projection hiding, re-enable '
                 'projection restore, workspace doctor checks, refreshTree metadata sync error visibility, and '
                 'last-good TreeView state preservation remain consistent.',
  'kind': 'native_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 67},
 {'id': 'f.workspace_local_control_consistent',
  'title': 'F workspace local control consistent',
  'description': 'F_0027 verifies local workspace CRUD, enable/disable/doctor, mode guards, delete guards, registry '
                 'conflicts, metadata resolver modes, and relay workspace sync.',
  'kind': 'local_verifier',
  'callable_path': '',
  'parameters': [],
  'returns': '',
  'notes': [],
  'order': 77})


def _check(name: str, ok: bool, detail: dict[str, Any]) -> dict[str, Any]:
    return {"name": name, "ok": bool(ok), "detail": detail}


def workspace_display(record: dict[str, Any]) -> str:
    return str(record.get("display_name") or record.get("display") or record.get("name") or "")


def workspace_local_enabled(record: dict[str, Any] | None) -> bool:
    if not record:
        return False
    if "local_enabled" in record:
        return record.get("local_enabled") is True
    if "enabled" in record:
        return record.get("enabled") is True
    return False


def workspace_record_matches_prefix(record: dict[str, Any], prefix: str) -> bool:
    display = workspace_display(record)
    workspace_id = str(record.get("workspace_id") or "")
    return display.startswith(prefix) or workspace_id.startswith("ws_" + prefix.lower())


def workspace_record_checks(
    display_name: str,
    *,
    local: dict[str, Any] | None,
    relay: dict[str, Any] | None,
    provider: str,
    mode: str,
    repo_url: str = "",
    repo_path: str = "",
) -> dict[str, Any]:
    detail = {"display_name": display_name, "local": local or {}, "relay": relay or {}}
    checks: list[dict[str, Any]] = []
    relay_required = not (provider == "local" and mode == "local_only")
    checks.append(_check("workspace_record_visible_" + display_name, bool(local and (relay or not relay_required)), detail))
    for source, record in (("local", local), ("relay", relay)):
        if record is None:
            continue
        checks.append(_check(f"{source}_workspace_provider_{display_name}", record.get("provider") == provider, record))
        checks.append(_check(f"{source}_workspace_mode_{display_name}", record.get("metadata_mode") == mode, record))
        if repo_url:
            checks.append(_check(f"{source}_workspace_repo_url_{display_name}", record.get("repo_url") == repo_url, record))
        if repo_path:
            checks.append(_check(
                f"{source}_workspace_repo_path_{display_name}",
                record.get("repo_url") == repo_path or record.get("local_path") == repo_path,
                record,
            ))
    if not relay_required:
        checks.append(_check(f"relay_workspace_absent_for_local_only_{display_name}", relay is None, detail))
    return {"detail": detail, "checks": checks}


def relay_workspace_sync_checks(
    display_name: str,
    *,
    local: dict[str, Any] | None,
    relay: dict[str, Any] | None,
    provider: str,
) -> dict[str, Any]:
    detail = {"display_name": display_name, "local": local or {}, "relay": relay or {}}
    checks = [
        _check("relay_workspace_sync_visible_" + display_name, bool(local and relay), detail),
    ]
    if local is not None and relay is not None:
        checks.extend([
            _check("relay_workspace_sync_provider_" + display_name, relay.get("provider") == provider, detail),
            _check(
                "relay_workspace_sync_mode_" + display_name,
                relay.get("metadata_mode") == local.get("metadata_mode"),
                detail,
            ),
        ])
    return {"detail": detail | {"synced": True}, "checks": checks}


def workspace_metadata_root_checks(
    workspace: dict[str, Any],
    resolver: dict[str, Any],
    mode: str,
    *,
    provider: str = "",
) -> dict[str, Any]:
    metadata_root = Path(str(resolver.get("metadata_root") or ""))
    local_path = Path(str(workspace.get("local_path") or resolver.get("workspace_source_path") or ""))
    detail = {"workspace": workspace, "resolver": resolver, "metadata_root": str(metadata_root), "local_path": str(local_path)}
    checks: list[dict[str, Any]] = []
    if mode == "repo_dotdir":
        checks.append(_check("repo_dotdir_metadata_root_under_repo", metadata_root == local_path / ".intern_workspace", detail))
    elif mode == "metadata_branch":
        checkout = Path(str(resolver.get("metadata_checkout_path") or ""))
        detail["metadata_checkout_path"] = str(checkout)
        checks.extend([
            _check("metadata_branch_checkout_present", (checkout / ".git").is_dir(), detail),
            _check("metadata_branch_root_under_checkout", metadata_root == checkout / ".intern_workspace", detail),
            _check("metadata_branch_not_repo_dotdir", metadata_root != local_path / ".intern_workspace", detail),
        ])
    elif mode == "local_only":
        checks.extend([
            _check("local_only_metadata_root_under_local_cache", "/metadata/local/.intern_workspace" in str(metadata_root), detail),
            _check("local_only_has_no_git_checkout", not resolver.get("metadata_checkout_path"), detail),
        ])
    else:
        raise ValueError("unsupported metadata mode assertion: " + mode)
    if provider:
        checks.append(_check("metadata_root_provider_" + provider, resolver.get("repo_provider") == provider, detail))
    return {"detail": detail, "checks": checks}


def metadata_branch_created_checks(
    workspace: dict[str, Any],
    resolver: dict[str, Any],
    ls_remote: dict[str, Any],
    *,
    provider: str,
) -> dict[str, Any]:
    result = workspace_metadata_root_checks(workspace, resolver, "metadata_branch", provider=provider)
    branch = str(workspace.get("metadata_branch") or "intern_workspace")
    detail = dict(result["detail"])
    detail["ls_remote"] = ls_remote
    checks = list(result["checks"])
    checks.append(_check("metadata_branch_remote_visible_" + branch, ls_remote.get("returncode") == 0 and bool(str(ls_remote.get("stdout") or "").strip()), detail))
    return {"detail": detail, "checks": checks}


def business_branch_unchanged_check(baseline: dict[str, Any], current: dict[str, Any], *, label: str) -> dict[str, Any]:
    detail = {"baseline": baseline, "current": current}
    return {
        "detail": detail,
        "checks": [
            _check(label.replace(" ", "_") + "_unchanged", current.get("revision") == baseline.get("revision"), detail),
        ],
    }


def workspace_absent_check(display_name: str, *, local: dict[str, Any] | None, relay: dict[str, Any] | None) -> dict[str, Any]:
    detail = {"display_name": display_name, "local": local or {}, "relay": relay or {}}
    return {
        "detail": detail | {"absent": True},
        "checks": [_check("workspace_record_absent_" + display_name, not local and not relay, detail)],
    }


def workspace_prefix_records(records: dict[str, list[dict[str, Any]]], prefix: str) -> dict[str, list[dict[str, Any]]]:
    return {
        source: [item for item in items if workspace_record_matches_prefix(item, prefix)]
        for source, items in records.items()
    }


def no_extra_workspace_records_check(
    prefix: str,
    records: dict[str, list[dict[str, Any]]],
    *,
    allowed_displays: set[str],
) -> dict[str, Any]:
    extras: list[dict[str, Any]] = []
    for source, items in records.items():
        for item in items:
            if workspace_display(item) not in allowed_displays:
                extras.append({"source": source, "record": item})
    detail = {"prefix": prefix, "allowed_displays": sorted(allowed_displays), "records": records, "extras": extras}
    return {
        "detail": detail,
        "checks": [_check("no_extra_workspace_records_" + prefix.rstrip("_"), not extras, detail)],
    }


def classify_workspace_attempt_failure(text: str) -> str:
    lowered = text.lower()
    if "already exists" in lowered or "duplicate" in lowered:
        return "duplicate_display_name"
    if "missing_branch" in lowered or "metadata branch checkout failed" in lowered or "remote branch" in lowered:
        return "branch_unavailable"
    if any(marker in lowered for marker in ("could not verify", "clone failed", "repository not found", "could not resolve hostname", "unreachable", "codeup.invalid")):
        return "repo_unreachable"
    return "unknown"


def workspace_attempt_failed_check(attempt: dict[str, Any], reason_kind: str) -> dict[str, Any]:
    detail = dict(attempt)
    return {
        "detail": detail,
        "checks": [
            _check(
                "workspace_attempt_failed_" + reason_kind,
                bool(attempt.get("failed_at")) and attempt.get("reason_kind") == reason_kind,
                detail,
            ),
        ],
    }


def require_checks(case: Any, result: dict[str, Any]) -> dict[str, Any]:
    for check in result["checks"]:
        case.require(check["name"], check["ok"], check["detail"])
    return result["detail"]


def no_feishu_group_allocated_check(name: str, payloads: tuple[Any, ...]) -> dict[str, Any]:
    forbidden = {"chat_id", "open_chat_id", "feishu_chat_id", "group_chat_id", "feishu_group_id"}
    violations: list[dict[str, str]] = []

    def scan(value: Any, path: str) -> None:
        if isinstance(value, dict):
            for key, item in value.items():
                key_text = str(key)
                next_path = f"{path}.{key_text}" if path else key_text
                if key_text in forbidden and item:
                    violations.append({"path": next_path, "value": "<redacted>"})
                scan(item, next_path)
        elif isinstance(value, list):
            for index, item in enumerate(value):
                scan(item, f"{path}[{index}]")

    for index, payload in enumerate(payloads):
        scan(payload, f"payload[{index}]")
    detail = {"checked_payloads": len(payloads), "violations": violations}
    return {"detail": detail, "checks": [_check(name, not violations, detail)]}
